/*
-- Query: SELECT * FROM embroidery.position
-- Date: 2023-03-12 22:56
*/
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (1,1,'Above Pocket LHS');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (2,1,'Above Pocket RHS');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (3,1,'Below Pocket LHS');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (4,1,'Below Pocket RHS');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (5,1,'Collar Bed LHS');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (6,1,'Collar Bed RHS');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (7,1,'Collar Bed Back');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (8,1,'Cuff LHS');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (9,1,'Cuff RHS');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (10,1,'Downside LHS');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (11,1,'Downside RHS');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (12,1,'Opposite Pocket LHS');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (13,1,'Opposite Pocket RHS');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (14,1,'Outer Collar LHS');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (15,1,'Outer Collar RHS');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (16,1,'Outer Collar Back');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (17,2,'Waistband');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (18,2,'Near Pocket LHS');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (19,2,'Near Pocket RHS');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (20,3,'Above Hem LHS');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (21,3,'Above Hem RHS');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (22,3,'Breast LHS');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (23,3,'Breast RHS');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (24,3,'Below Collar');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (25,4,'Along Zip');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (26,4,'Waistband');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (27,5,'Top');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (28,6,'Bottom LHS');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (29,6,'Bottom RHS');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (30,6,'Chest LHS');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (31,6,'Chest RHS');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (32,6,'Collar Bed');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (33,6,'Outer Collar Back');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (34,6,'Ribbon Back');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (35,7,'Above Hem LHS');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (36,7,'Above Hem RHS');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (37,7,'Above Logo');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (38,7,'Below Logo');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (39,7,'Chest LHS');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (40,7,'Chest RHS');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (41,7,'Inner Collar');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (42,7,'Inside Yoke');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (43,7,'Near Pocket LHS');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (44,7,'Near Pocket RHS');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (45,7,'Outer Collar');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (46,8,'Above Logo');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (47,8,'Below Logo');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (48,8,'Bottom LHS');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (49,8,'Bottom RHS');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (50,8,'Chest LHS');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (51,8,'Chest RHS');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (52,9,'Above Top Pocket');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (53,9,'Below Bottom Pocket LHS');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (54,9,'Below Bottom Pocket RHS');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (55,9,'Below Flap LHS');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (56,9,'Below Flap RHS');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (57,9,'On Flap LHS');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (58,9,'On Flap RHS');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (59,10,'Handkerchief');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (60,12,'Hem LHS');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (61,12,'Hem RHS');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (62,12,'Near Pocket LHS');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (63,12,'Near Pocket RHS');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (64,12,'Waistband');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (65,13,'Above Logo');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (66,13,'Below Logo');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (67,13,'Hip LHS');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (68,13,'Hip RHS');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (69,13,'Near Pocket LHS');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (70,13,'Near Pocket RHS');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (71,13,'Opposite Logo');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (72,13,'Outer Collar');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (73,13,'Inner Collar');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (74,15,'Front');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (75,15,'Back');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (76,17,'Chest LHS');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (77,17,'Chest RHS');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (78,17,'Hem LHS');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (79,17,'Hem RHS');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (80,17,'Hip LHS');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (81,17,'Hip RHS');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (82,17,'Back Below Neck');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (83,18,'Top');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (84,19,'On Fold');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (85,19,'Under Fold');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (86,20,'Center');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (87,20,'Top LHS');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (88,20,'Top Middle');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (89,20,'Top RHS');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (90,21,'Center');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (91,21,'Top LHS');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (92,21,'Top Middle');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (93,21,'Top RHS');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (94,22,'Center');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (95,22,'Top LHS');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (96,22,'Top Middle');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (97,22,'Top RHS');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (98,23,'Center');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (99,23,'Top LHS');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (100,23,'Top Middle');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (101,23,'Top RHS');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (102,24,'Center');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (103,24,'Top LHS');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (104,24,'Top Middle');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (105,24,'Top RHS');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (106,25,'Under Palm');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (107,26,'White Patch');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (108,27,'Above Pocket');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (109,27,'Inner Collar');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (110,28,'Near Hem LHS');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (111,29,'Back');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (112,30,'On Breast');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (113,30,'On Hem');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (114,30,'On Skirt');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (115,31,'Center');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (116,31,'Top LHS');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (117,31,'Top Middle');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (118,31,'Top RHS');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (119,33,'Below Waistband');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (120,35,'Chest Centre');
INSERT INTO `` (`id`,`item_id`,`name`) VALUES (121,34,'Special');
